### ISSUE TITLE
opprydding

### ISSUE THREAD

**Issue by arve0** [kwrl/trondheim.kodeklubben.no#3]
Fiks feks denne;
```
$ ./manage.py syncdb
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/arve/.virtualenvs/kodeklubben-trondheim/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/arve/.virtualenvs/kodeklubben-trondheim/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/arve/.virtualenvs/kodeklubben-trondheim/lib/python2.7/site-packages/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/arve/.virtualenvs/kodeklubben-trondheim/lib/python2.7/site-packages/django/core/management/__init__.py", line 75, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/Users/arve/.virtualenvs/kodeklubben-trondheim/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/arve/.virtualenvs/kodeklubben-trondheim/lib/python2.7/site-packages/south/management/commands/__init__.py", line 10, in <module>
    import django.template.loaders.app_directories
  File "/Users/arve/.virtualenvs/kodeklubben-trondheim/lib/python2.7/site-packages/django/template/loaders/app_directories.py", line 25, in <module>
    raise ImproperlyConfigured('ImportError %s: %s' % (app, e.args[0]))
django.core.exceptions.ImproperlyConfigured: ImportError ckeditor: No module named ckeditor
```

**Comment by kwrl** [comment]
Will do, sikkert bare manglende pakke i requirements.

**Comment by arve0** [comment]
trur ikke vi bruker ckeditor?

**Comment by kwrl** [comment]
newsfeed :)

**Comment by kwrl** [comment]
Brukes til å lage poster på siden.

**Comment by kwrl** [comment]
La til ckeditor i required_packages
